### ISSUE TITLE
[New Feature]: Multiple AI Model Support

### ISSUE THREAD

**Issue by riverma** [NASA-AMMOS/slim-cli#3]
**Checked for duplicates**

Yes - I've already checked

**Alternatives considered**

> Have you considered alternative solutions to your feature request?

Yes - and alternatives don't suffice

**Related problems**

> Is your feature request related to any problems? Please help us understand if so, including linking to any other issue tickets.

Currently only a single model is supported at a time, even if the model is not accessible to the user.

**Describe the feature request**

> A clear and concise description of your request. 

It'd be great to have the following type of user interaction:

`python slim-cli.py ... --use-ai <MODEL_ID>`

Where, `<MODEL_ID>` is one of:
- `openai-chatgpt4o`
- `azure-chatgpt4o`
- `llama3.1-70b`
- `llama3.1-400b`

For each of the above, there should be a check to ensure required environment variables are set, and if they are not, the program should exit. For example, the first model, the environment variable `OPENAI_KEY` should be set. 

Additionally, the argparse usage and the README should document the models and when to use which.

**Comment by yunks128** [comment]
This is integrated, and an error message is included when `OPENAI_KEY` is missing. 
Example:
```
python slim-cli.py ... --use-ai openai/gpt-4o
python slim-cli.py ... --use-ai azure/gpt-4o
python slim-cli.py ... --use-ai ollama/llama3.1:70b
```
